# =====================================================
# CONFIGURAÇÕES GERAIS
# =====================================================

quarkus.datasource.db-kind=postgresql

quarkus.http.test-port=8082


quarkus.openapi-generator.codegen.spec.openapi_yml.model-name-prefix=QuarkusOpenApiGenerator
quarkus.openapi.generator.spec=openapi.yml

# JWT
mp.jwt.verify.issuer=unitins-jwt
mp.jwt.verify.publickey.location=token/publicKey.pem
smallrye.jwt.sign.key.location=token/privateKey.pem

%prod.mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
%prod.smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}

# CORS habilitado
quarkus.http.cors=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,origin
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=24H

# =====================================================
# DESENVOLVIMENTO (DEV)
# =====================================================

%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=123456
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/eventos

%dev.quarkus.hibernate-orm.database.generation=update

# logs SQL no dev
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.bind-parameters=true

# CORS liberado no dev
%dev.quarkus.http.cors.origins=*

# =====================================================
# PRODUÇÃO (PROD)
# =====================================================

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# segurança no banco
%prod.quarkus.hibernate-orm.database.generation=validate

# Flyway
%prod.quarkus.flyway.migrate-at-start=true
%prod.quarkus.flyway.baseline-on-migrate=true
%prod.quarkus.flyway.clean-disabled=true

# logs limpos
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.hibernate-orm.log.bind-parameters=false

# liberar só frontend real
%prod.quarkus.http.cors.origins=${CORS_ORIGINS}

